<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Version>0.6</Version>

		<AssemblyName>etcd-terminal</AssemblyName>
		<RootNamespace>EtcdTerminal.App</RootNamespace>
		<OutputType>Exe</OutputType>
		<DebugType>none</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\EtcdTerminal\EtcdTerminal.csproj" />
		<ProjectReference Include="..\EtcdTerminal.Infrastructure\EtcdTerminal.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.57.2" />
		<PackageReference Include="Simplify.DI" Version="4.3.0" />
		<PackageReference Include="Simplify.System" Version="1.6.3" />
	</ItemGroup>
</Project>