name: Build

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore solution
        run: dotnet restore src/EtcdTerminal.slnx

      - name: Build solution
        run: dotnet build src/EtcdTerminal.slnx --configuration Release --no-restore
